### ISSUE TITLE
... not properly marking the file with a relevant scope

### ISSUE THREAD

**Issue by BlaM** [hedefalk/atom-vue#10]
https://github.com/AtomLinter/linter-htmlhint/issues/49 :

> Looks like this is an issue with language-vue not properly marking the file with a relevant scope, as such Atom is attempting to guess the scope and giving it text.html.basic, which this linter says it can handle.
> 
> You should report this as an issue over on the language-vue package, [...]

Which I hereby do... Not sure how all this scoping works, but text.html.basic seems not to be the correct scope for vue files.

**Comment by hedefalk** [comment]
Hm, ok - so what would be the correct scope name then? Is there any "html.fragment" or something like that we can use instead?

**Comment by aidistan** [comment]
Let's use `text.html.vue` instead.
