### ISSUE TITLE
wrong auto-closing brace in scss style, example in gif

### ISSUE THREAD

**Issue by anrananran** [hedefalk/atom-vue#100]
if I press enter next to the brace,  wrong auto-closing brace created: 
<img src="https://s2.ax1x.com/2019/07/04/ZU35nK.gif" alt="ZU35nK.gif" border="0">

if I insert a space, then press enter, there is no wrong brace create:
<img src="https://s2.ax1x.com/2019/07/04/ZU3I0O.gif" alt="ZU3I0O.gif" border="0">

thanks for your help!

**Comment by aidistan** [comment]
Hi @anrananran, `language-vue` does not close braces automatically. Please check the package which provides this feature instead.

**Comment by anrananran** [comment]
ok, i will check it, Thanks
