### ISSUE TITLE
Incomplete scopes for "/>" and "</" causing ligatures not to render

### ISSUE THREAD

**Issue by jonboiser** [hedefalk/atom-vue#103]
Here are some examples using the new Jetbrains Mono font, which has ligatures for `/>` and `</`.

Basically, it seems that
1. `</` is not ligatured correctly if it is in an end tag for an empty element.
1. `/>` is not ligatured correctly if it is used in a self-closing element that is not in the subset of HTML elements that are self-closable. So custom self-closing Vue components will not have that end bracket ligatured.

Based on [this issue from Fira Code](https://github.com/tonsky/FiraCode/issues/63), the syntax highlighting grammars need to tokenize ligatures together. So if the two parts of a ligature are tokenized separately with different scopes, they won't be rendered as a ligature. I tried to confirm this by manually grouping these characters together under a single node inside the Dev Tools.

Here's a screenshot, and I've pasted the text below with debugging comments

<img width="930" alt="Screen Shot 2020-01-16 at 11 26 19 AM" src="https://user-images.githubusercontent.com/10248067/72556278-23a9e800-3853-11ea-97ac-88aec28905a4.png">

I'd be happy to submit a PR if you can point me to which part in the grammar needs to be fixed. I'm comfortable working and testing on this library.

```
  <div>
    <!-- "</" OK -->
    <!-- Both chars have punctuation.definition.tag.begin.html -->
    <span>Hello</span>
    <!-- "</" Not OK -->
    <!-- "<" has an additional meta.scope.between-tag-pair.html scope 
        Which causes the two characters to be rendered in separate nodes -> no ligature
    -->
    <span></span>
    
    <!-- "/>" OK -->
    <!-- Both chars have punctuation.definition.tag.end.html -->
    <input />
    <!-- "/>" Not OK -->
    <!-- Only ">" has the scope -->
    <CustomInput />
  </div>

```

**Comment by aidistan** [comment]
Guess the scope "meta.scope.between-tag-pair.html" is just for the `<span></span>` case?

**Comment by jonboiser** [comment]
I'm not sure what the intention of the `meta.scope.between-tag-pair.html` scope is. I don't think the '<' with this scope would be syntaxed-highlighted differently by most themes, and doubt it's used for any other plugins.

In my personal branch of atom-vue, I actually removed this scope completely from the capture groups.

**Comment by aidistan** [comment]
I'm not sure about the intention either 😃

But I think it's better to stay the same with [the official syntax package](https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L19).
