### ISSUE TITLE
Answering a Call for Maintainers

### ISSUE THREAD

**Issue by confused-Techie** [hedefalk/atom-vue#118]
@hedefalk Hello, I'm confused-Techie from the Pulsar team.

I noticed your package README is asking for maintainers, I'd be more than happy to help out here if you're still open to it! (I fully realize your README was last updated about 2 years ago).

So hopefully this is the best way to contact you, since otherwise I didn't see an email address to do so otherwise.

Thanks for your time, would love to hear back from you!

**Comment by hedefalk** [comment]
Hi!

Yes, I'm not using Atom or Pulsar so if you want to take on maintaining this, that'd be great!

**Comment by confused-Techie** [comment]
Of course, I'd be more than happy to see what I can do here! @hedefalk To continue then do you have a preference? Or would you like to just give me admin access to this repo? What ever works for you best. Thanks a ton for taking the time to respond

**Comment by zhaolinlau** [comment]
> Of course, I'd be more than happy to see what I can do here! @hedefalk To continue then do you have a preference? Or would you like to just give me admin access to this repo? What ever works for you best. Thanks a ton for taking the time to respond

@hedefalk any update regarding this?

**Comment by hedefalk** [comment]
Sorry for slow reply. @confused-Techie, did you get an invite?

**Comment by confused-Techie** [comment]
@hedefalk No worries at all for taking your time. Thanks a ton for adding me! I've received the invite and accepted it as well!

If I could ask one last question of you before leaving you alone to work on your current projects, is there any goals or guiding principals that are important to you within this repository? Or as long as the package continues working is that your only priority?

Essentially, I want to make sure the level of freedom you are comfortable providing here, before I move on to start making changes, want to make sure I'm not stepping on any toes.

Again thanks a ton for adding me, and appreciate you!

**Comment by hedefalk** [comment]
Thanks @confused-Techie!

No need to worry about my toes at all. I just want the best for anyone using it so I'm really happy with any help on that :) 

Basically, this repo started out with me using vue and Atom pretty early on and I think I took Evan You's Sublime grammar and converted it to Atom. Then it has been a community effort to keep it up-to-date and I guess it has fallen behind quite a bit.

Personally I switched to vscode and I'm using Volar now for any vue.js work.

**Comment by confused-Techie** [comment]
Well in that case glad to hear it. I'll keep on that legacy of just trying to provide the best experience for any users of Vue in Atom/Pulsar as best I can then, while of course not committing to anything, as I personally don't use Vue, just a person who wants all packages to continue to work.

Thanks a ton again for your support in letting this happen, and trusting me with the repo!
