### ISSUE TITLE
Emmet support

### ISSUE THREAD

**Issue by Cweili** [hedefalk/atom-vue#15]
Emmet not support in `<template>` tag.
https://github.com/emmetio/emmet-atom

**Comment by aidistan** [comment]
@Cweili We will look into it and I suggest you to open the same issue in `emmet-atom` for help.

**Comment by aidistan** [comment]
@Cweili This issue is unrelated to `atom-vue` package. To get what you want, please add following key binding in your `keymap.cson` file:

``` cson
'atom-text-editor[data-grammar="text html vue"]:not([mini])':
  'tab': 'emmet:expand-abbreviation-with-tab'
```

References:
1. https://github.com/emmetio/emmet-atom#tab-key
2. https://github.com/emmetio/emmet-atom/pull/373/files

**Comment by Cweili** [comment]
@aidistan Great! Problem solved! Thanks for your nice work!

**Comment by ghost** [comment]
It is great for html syntax, but for example, jade or stylus are still without support snippets... :(

**Comment by aidistan** [comment]
@frontendthug Please try to modify the `keymap.cson` file on your own, following the example above.

I am quite sorry that I could not give any further help, since this issue is unrelated to `atom-vue` itself and I am not familiar with `Emmet`.
