### ISSUE TITLE
Stylus syntax not colored with stylus package 2.1.2

### ISSUE THREAD

**Issue by tikiatua** [hedefalk/atom-vue#17]
Hi there,

many thanks for this great plugin. There seems to be an issue with the newest stylus atom package – version 2.1.2 – as the syntax coloring is completely disabled (running Atom Beta 1.5.0-beta3 on OS X).

Any help would be greatly appreciated.

**Comment by aidistan** [comment]
@tikiatua Try to update to v0.9.0 plz :smile:

**Comment by tikiatua** [comment]
Awesome. The new version works like a charm again. Thank you very much for the quick response.
