### ISSUE TITLE
Ctrl + R doesn't work

### ISSUE THREAD

**Issue by whwnow** [hedefalk/atom-vue#19]
Hi~
I used "ctrl + r" to find the method. but it doesn't work in the  vue file

| Keystroke | Command | Source | Selector |
| --- | --- | --- | --- |
| ctrl-r | symbols-view:toggle-file-symbols | Symbols View | platform-win32 atom-text-editor |

**Comment by aidistan** [comment]
@whwnow Since [Ctags](http://ctags.sourceforge.net/) used by [atom/symbols-view](https://github.com/atom/symbols-view) does [NOT support `vue` yet](http://ctags.sourceforge.net/languages.html), I guess there is no easy solution.

**Comment by whwnow** [comment]
well, thank you anyway...

**Comment by aidistan** [comment]
@whwnow 

FYI. Recently I'm working on an atom plugin based on Ctags and found the solution to this issue: update the default [_ctags-config_](https://github.com/atom/symbols-view/blob/master/lib/ctags-config) used in `symbols-view`. Since I've no idea what symbols you need to show, I could only give an example. Just change it as you like:

```
--langdef=Vue
--langmap=Vue:.vue
--regex-Vue=/^[ \t]*([A-Za-z_$][A-Za-z0-9_$]+)[ \t]*:[ \t]*function[ \t]*\(/\1/f,function/
```

**Reference** : [How to Add Support for a New Language to Exuberant Ctags](http://ctags.sourceforge.net/EXTENDING.html)

**Comment by wprater** [comment]
@aidistan is there a way to extend that file vs. overriding it?

**Comment by aidistan** [comment]
@wprater The answer for `ctags` is yes but for `symbols-view` is no. Since `symbols-view` does not support providing extra command-line options for `ctags`, you may need to find a better replacement.

**Comment by aidistan** [comment]
@wprater I found there are some default option files (if exist) for `ctags`, like _PROJECT_ROOT/.ctags_, which you could use to extend ctags options instead of overriding that file. See http://ctags.sourceforge.net/ctags.html#FILES for more info.

**Comment by jinglesthula** [comment]
Is there an alternative to symbols-view?  It seems like it wouldn't be too difficult to have something that could run a simple regex and then people could provide whatever regexes they want.  I haven't hacked on Atom to know how bad of an idea that might be. :)

**Comment by aidistan** [comment]
@jinglesthula `symbols-view` has already change the default shortcut. Why to bother yourself to find an alternative? What extra features do you need?

**Comment by jinglesthula** [comment]
It's not the shortcut I'm worried about - just that `symbols-view` says no symbols found when I use the shortcut.  In my case, the language I'm coding in doesn't appear to be supported.  I will try the other suggestions you mentioned above to see if those work though.
