### ISSUE TITLE
Incorrect syntax highlighting for ES6 script?

### ISSUE THREAD

**Issue by xream** [hedefalk/atom-vue#20]
<img width="950" alt="2016-04-07 17 50 50" src="https://cloud.githubusercontent.com/assets/1210282/14347378/6d6cd4ba-fce9-11e5-884f-65e545b65835.png">

**Comment by aidistan** [comment]
@xream 

![selection_003](https://cloud.githubusercontent.com/assets/3037661/14349023/c43c737c-fc85-11e5-97b4-32421d590cd0.png)

![selection_002](https://cloud.githubusercontent.com/assets/3037661/14349024/c5bf9d14-fc85-11e5-8ba1-33a3c6de2b1d.png)

**Comment by hedefalk** [comment]
They say an a picture is worth a thousand words, but I don't get it :)

**Comment by xream** [comment]
I think you use 'JavaScript' to show ES6 syntax highlighting. But we prefer 'JavaScript with JSX' or something like that which support ES6 syntax.

![image](https://cloud.githubusercontent.com/assets/1210282/14372881/42e34308-fd77-11e5-9faf-5f09e8d46631.png)

![image](https://cloud.githubusercontent.com/assets/1210282/14372884/48bdd702-fd77-11e5-92ae-d90c711ae75c.png)

**Comment by aidistan** [comment]
@hedefalk Haha, you got me. That's actually what I was trying to say: "I don't understand."

**Comment by aidistan** [comment]
@xream Now I have understood what's the problem.

I'm sorry that we only support the core package `language-javascript` other than `language-javascript-jsx`. To get you want, you have to hack this package loaclly:
1. open the grammar file of `language-vue` package (~/.atom/packages/language-vue/grammars/vue.cson)
2. replace `include: "source.js"` with `include: "source.js.jsx.react"`
3. reload Atom by `ctrl + alt + R`
4. done

Note: package update will reset this temporal hacking.

**Comment by xream** [comment]
I think hacking this package loaclly is not the right way...
Maybe it's better to tell users to add `lang=babel` in `script` and  make this package support `(?:^\\s+)?(<)((?i:script))\\b(?=[^>]*lang=[\"']babel[\"'])`, just like how we support CoffeeScript by adding 'lang=coffee'.

**Comment by aidistan** [comment]
It seems better but against a philosophy when I write packages: do only the minimum.

In my opinion,
1. CoffeeScript is not in the same situation as this one, since it's supported by the core package `language-coffee-script`. Here `language-javascript-jsx` is a community one and has a scope named `source.js.jsx.react` which smells bad and brings the second issue.
2. There are several community packages supporting ES6 syntax highlighting. Which name should we use? `babel` is obviously a bad choice, as there exists a package named `language-babel` with another scope `source.js.jsx`.

**Comment by xream** [comment]
OK. I understand the philosophy.

By the way, `vue-loader` uses `babel-loader` by default. So If we use `lang=babel`, it will not affect anything.

**Comment by aidistan** [comment]
Thanks for pointing out that. I forgot the `lang` attribute affects loaders too.

What I said is it's a bit awkward that scripts annotated by `lang=babel` are highlighted by `language-javascript-jsx` rather than `language-babel`. Isn't it?

**Comment by xream** [comment]
You are right. My bad.😝
