### ISSUE TITLE
problem with coloring

### ISSUE THREAD

**Issue by rlataguerra** [hedefalk/atom-vue#22]
I think the last update introduced a bug.
Here is a screenshot:

<img width="885" alt="capture d ecran 2016-04-11 a 22 59 40" src="https://cloud.githubusercontent.com/assets/2256150/14442307/513f6c50-0039-11e6-9916-c16f83ed1a00.png">

**Comment by aidistan** [comment]
Double quotes are missing around the value of `:entries`.

![selection_002](https://cloud.githubusercontent.com/assets/3037661/14449262/c731fc46-0036-11e6-943a-93cf5535786d.png)
![selection_001](https://cloud.githubusercontent.com/assets/3037661/14449263/c9b742e6-0036-11e6-9bba-c394982363b3.png)

http://vuejs.org/guide/syntax.html#Shorthands

**Comment by rlataguerra** [comment]
my bad, you're right

thanks
