### ISSUE TITLE
support for pug

### ISSUE THREAD

**Issue by paulpflug** [hedefalk/atom-vue#23]
jade was renamed to pug.
Syntax highlighting doesn't work..

``` vue
<template lang="pug">
div.class
</template>
```

I think support for jade should stay, for backwards compatibility.

**Comment by paulpflug** [comment]
thanks :+1:

**Comment by voanhcuoc** [comment]
It's all complicated :
@paulpflug : to make it work, I must specify `lang='jade'` and install _pug_ npm package
@hedefalk : and when I do `lang='jade'` , language-vue don't render anymore

**Comment by aidistan** [comment]
@voanhcuoc 

It's simple all the time. Use `lang='jade'` with `language-jade` atom package and `jade-loader` npm package, or `lang='pug'` with `language-pug` atom package and `pug-loader` npm package.
