### ISSUE TITLE
Non English Keyboard Issue

### ISSUE THREAD

**Issue by greven** [hedefalk/atom-vue#26]
When using atom-vue and with a non English keyboard layout I can't insert a colon symbol anymore.
If I change to a English layout I don't have this problem. But since my keyboard is in this case portuguese it is an hassle. Instead of the colon (:) it inserts > > > >.

I can workound it by copy pasting the colon, but would be awesome to have this fixed.

**Comment by aidistan** [comment]
@greven I can't see any relation between the keyboard issue and `atom-vue`. Does that only happen when writing a vue component?

**Comment by greven** [comment]
@aidistan Yes only when writting vue components. I tested on atom in Linux and Windows and same behaviour happen. I guess the problem could be in Atom itself somehow.

Anyway I opened the issue since I didn't see it before and was hoping someone experienced the same.
Sorry can't really add much more data than this.
If no one complains about the same problem feel free to close it, it might be tied to Atom.

**Comment by aidistan** [comment]
@greven That's really weird since `atom-vue` does not pre-process or post-process your input. Let's see if anyone else meet the same issue.

**Comment by aidistan** [comment]
@greven Remember to keep up your Atom with the latest version. Maybe it would solve this weird problem.

**Comment by greven** [comment]
It is. It is really wierd this bug or whatever it is. I need to change the keyboard to English in order to use the colon. It only happens inside the .vue components which is odd.
Anyway I guess there is no point to keep the issue open. Although it happens only with .vue files it might not even be related to your plugins, which I rather enjoy so thank you for that.

If you want you can close the issue. Thanks anyway.
