### ISSUE TITLE
Support for Ctrl-D in <template>

### ISSUE THREAD

**Issue by danieldiekmeier** [hedefalk/atom-vue#27]
When using `Ctrl-D` in an ordinary HTML file, you can select the containing scope. You can press `Ctrl-D` multiple times to expand the scope further. This is quite handy in some cases, but sadly, this doesn't work in atom-vue. I'm not sure why it doesn't work, but can this be added?

**Comment by aidistan** [comment]
@danieldiekmeier `ctrl-d` here in my Atom (v1.7.4) binds to `find-and-replace:select-next` provided by a core package `Find And Replace` and it has the same function in files with any extension, including `html` and `vue`.

**Comment by danieldiekmeier** [comment]
Yes, you're right. It was a problem with my configuration.
