### ISSUE TITLE
May I use the source code to create a new Atom Package?

### ISSUE THREAD

**Issue by coffeedeveloper** [hedefalk/atom-vue#29]
[Weex](http://alibaba.github.io/weex/index.html) is something like Vue Navtive. It syntax also like Vue Component, but have some difference.
I wanna to create a Weex syntax package in Atom. Named **language-weex**.
So, may I use your source code ? ^_^

**Comment by aidistan** [comment]
I guess it's OK, since `vuejs/vue-syntax-highlight` uses an MIT license. What's your opinion? @hedefalk

**Comment by hedefalk** [comment]
Sure thing! I'll add an MIT LICENSE file.

**Comment by coffeedeveloper** [comment]
I'll add an MIT LICENSE file too. 😉

**Comment by hedefalk** [comment]
@aidistan Did I get your name correct? https://github.com/hedefalk/atom-vue/blob/master/LICENSE

**Comment by aidistan** [comment]
@hedefalk Yep
