### ISSUE TITLE
Highlighting data broken on hyphened props

### ISSUE THREAD

**Issue by miljan-aleksic** [hedefalk/atom-vue#30]
Hi, thanks for this plugin!

The following code is getting hihglighted as expected:

```
:prop="[{
  bar: foo
}]"
```

While this one doesn't:

```
:prop-prop="[{
  bar: foo
}]"
```

It would be nice to support it as well :)

**Comment by aidistan** [comment]
Hi, thanks for the issue.

I am a bit confused with your example code. Could you give a complete vue-component example file (with `template`, `script` and `style`) please?

**Comment by miljan-aleksic** [comment]
Probably a screenshot will help :)

![screen shot 2016-07-16 at 14 33 42](https://cloud.githubusercontent.com/assets/513275/16893452/61e3e2b0-4b62-11e6-996a-b93ed1a979b5.png)

**Comment by aidistan** [comment]
Done. Enjoy v0.14.1~
