### ISSUE TITLE
HTML code not highlighted

### ISSUE THREAD

**Issue by Wang-Kai** [hedefalk/atom-vue#33]

**Comment by aidistan** [comment]
Please describe the issue in detail, including your working environment, steps to reproduce the issue, screenshots, etc...

**Comment by Wang-Kai** [comment]
![laloacxui80hgm0eoa_1080_1920 png_620x10000q90](https://cloud.githubusercontent.com/assets/13144386/17691053/07be8d78-63c5-11e6-8fd2-22af3833bbc5.jpg)


Sorry,  my English is poor. In my mac (OS 10.11.6), the attributes in HTML tag do not have color ..

**Comment by Wang-Kai** [comment]
<img width="782" alt="2016-08-16 3 20 12" src="https://cloud.githubusercontent.com/assets/13144386/17691141/6f8a5162-63c5-11e6-9b10-1f43b190d1b5.png">

Sorry, my English is poor. In my mac (OS 10.11.6), the attributes in HTML tag do not have color ..

**Comment by aidistan** [comment]
@Wang-Kai 你只给了部分截图，不能准确判断问题所在，只能大概推测你的文件可能不符合 `.vue` 的语法规范。如果希望获得进一步帮助，请把这个文件作为附件传上来。

**Comment by Wang-Kai** [comment]
我突然发现我的atom里根本就没装atom-vue这个package, 我搜了一下，也没有搜到atom-vue这个包。我就想问问：我的.vue文件中，HTML 代码没有高亮，请问又啥解决方案吗？

**Comment by aidistan** [comment]
请安装一下 language-vue

**Comment by Wang-Kai** [comment]
安装了呀，还是没有高亮，求帮忙！

[search.vue.zip](https://github.com/hedefalk/atom-vue/files/419749/search.vue.zip)

**Comment by aidistan** [comment]
`search.vue` 在我这里的高亮一切正常，可能是你那里环境配置的问题。

如果你搞不定，抽空给你远程协助一下吧。

**Comment by Wang-Kai** [comment]
问题解决了，language-vue和其他插件有冲突，卸了几个插件就好了 。。多谢解答！
