### ISSUE TITLE
Not working with language-pug.

### ISSUE THREAD

**Issue by tiaod** [hedefalk/atom-vue#36]
Not working with [`language-pug`](https://github.com/genoma/language-pug/issues)(was jade).

**Comment by aidistan** [comment]
Please refer to #23

**Comment by tiaod** [comment]
Thank you!

**Comment by tiaod** [comment]
Sorry. I found the reason. I had forgot to upgrade `language-vue`. After upgrade this package and restart Atom, it works! :smiley:

**Comment by aidistan** [comment]
Thanks for leaving your solution here :smiley:
