### ISSUE TITLE
Feature request: syntax highlighting for "async" keyword on vue instance methods

### ISSUE THREAD

**Issue by brendanbowidas** [hedefalk/atom-vue#41]
Currently, when using async functions on a vue method, the `async` keyword has no syntax highlighting.
e.g :

``` javascript
  export default {
      methods: {
        async foo() {
           const result = await bar()
         }
      }
  }
```

**Comment by aidistan** [comment]
It works fine in my Atom:

![selection_001](https://cloud.githubusercontent.com/assets/3037661/19549228/bcbc5f5e-9668-11e6-8ccc-4dded2e8e5b8.png)

Try to upgrade your Atom or `language-javascript` package at least.
