### ISSUE TITLE
atom-typescript support

### ISSUE THREAD

**Issue by snaptopixel** [hedefalk/atom-vue#43]
Is there a way to get atom-typescript working for `<script lang="ts">`?

**Comment by snaptopixel** [comment]
Thanks @aidistan! This doesn't actually get intellisense etc working though :(

Is there a way to get atom-typescript to treat the code between `<script lang="ts">` tags as if it were in a .ts file? Maybe @TypeStrong has some ideas?

**Comment by aidistan** [comment]
@snaptopixel It works actually. The only thing you need to do is to **install a typescript grammar package** (to handle `script.ts` scope). Since `language-typescript` is deprecated now, I have tested with `language-ts` and `language-typescript-grammars-only`. Either is fine.

**Comment by snaptopixel** [comment]
@aidistan you have autocomplete and type checking working between `<script lang="ts">` tags?  I installed the grammars-only package and get snippets and such, but it doesn't type check anything... Here's what I'm looking for (this is from a .ts file)...
![](https://d3vv6lp55qjaqc.cloudfront.net/items/1D2p2d3S2K2H1h040W3u/Image%202016-11-22%20at%2010.24.48%20AM.png)

**Comment by aidistan** [comment]
@snaptopixel Guess we have to request the type-checking package to support `ts` scope rather than *.ts* files only.

**Comment by cybernetlab** [comment]
Ideally whould be to integrate with [atom-typescript](https://atom.io/packages/atom-typescript) extension

**Comment by shaunc** [comment]
@aidistan -- It doesn't seem like this was resolved. Why is it closed? Should I open a new issue?
