### ISSUE TITLE
support vue syntax highlighting custom extension 

### ISSUE THREAD

**Issue by alidcast** [hedefalk/atom-vue#47]
Is it possible to configure atom-vue to support syntax highlighting for an extension other than `.vue`?

For example, I'm using [vue-markdown-loader](https://github.com/QingWei-Li/vue-markdown-loader) to convert markdown files to Vue components. It'd be helpful to include highlighting for the script tags inside the markdown files.

**Comment by aidistan** [comment]
Please refer to #14. Think it would be helpful.

**Comment by alidcast** [comment]
Yes, the approach mentioned in the issue made it work. Thanks!
