### ISSUE TITLE
Advantages over treating .vue file as .html file

### ISSUE THREAD

**Issue by zigomir** [hedefalk/atom-vue#48]
Hey! Thanks for this package, I'm a long time user myself.

Today I got a fresh Atom install after some time and first tried to open `.vue` file as `.html` file (can be configured with `file-types` package too automate) and found out I get html, css and js highlighting and standard Atom code completion & snippets support.

I'm curious, is this something new for Atom or did they add this lately? Then I'm curious what `atom-vue` gives you in addition to that?

**Comment by aidistan** [comment]
Standard templates, scripts and styles are highlighted correctly in `.html` files (without vue directive highlighting). However, when it comes to `pug`, `ts` or `scss`, you will need `atom-vue` to handle with the scopes.

**Comment by zigomir** [comment]
I see, thanks!
