### ISSUE TITLE
Unexpected Token <

### ISSUE THREAD

**Issue by codeofsumit** [hedefalk/atom-vue#49]
When I have a `script` tag inside a vue single file component, I get this error for the `template` tag part.

![image](https://cloud.githubusercontent.com/assets/2399810/21183243/59f82842-c207-11e6-9586-4192c408bd69.png)

Anything I can do that atom/es-lint knows this is valid?

**Comment by aidistan** [comment]
Maybe [AtomLinter/linter-eslint](https://github.com/AtomLinter/linter-eslint/issues) is the right place to ask this question?

**Comment by codeofsumit** [comment]
@aidistan I don't think it's an issue with AtomLinter because the `eslint` command in the CLI gives me the same error
![image](https://cloud.githubusercontent.com/assets/2399810/21256229/64cb6138-c371-11e6-8327-4ed805517a8b.png)

I asked it here because well, maybe you guys are using eslint with single-file-components as well - don't you have this issue? I'll post this here https://github.com/BenoitZugmeyer/eslint-plugin-html as well
