### ISSUE TITLE
Support SASS syntax correctly

### ISSUE THREAD

**Issue by aidistan** [hedefalk/atom-vue#5]
There are two syntaxes available for Sass. The new one, known as SCSS (Sassy CSS) and recommanded by Sass, is an extension of the syntax of CSS and more widely used today. And the sass loader for Webpack, [sass-loader](https://www.npmjs.com/package/sass-loader), only processes `.scss` files as described in its document.

Thus we have to write styles like this in `.vue` files

```
<style lang="sass">
</style>
```

which should be highlighted in SCSS syntax, not in SASS syntax.

It's a little weird. So I open this issue for discussion instead of sending a PR to correct directly.

**Comment by aidistan** [comment]
And I found this issue is somehow related to #4.

**Comment by hedefalk** [comment]
But can't you just write

```
<style lang="scss">
</style>
```

and everything's happy-go-lucky?

**Comment by aidistan** [comment]
There is no special handling for this in [vue-loader](https://github.com/vuejs/vue-loader). The `lang` attribute will be passed directly to find a corresponding loader, which raises loader-not-found errors when I write like that.

Related lines:
- https://github.com/vuejs/vue-loader/blob/master/lib/parser.js#L18
- https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L67
- https://github.com/vuejs/vue-loader/blob/master/lib/loader.js#L86

**Comment by hedefalk** [comment]
And you have tried:

{ test: /.scss$/, loader: "style!css!sass" },

as I suggested on #4?

**Comment by hedefalk** [comment]
AH, ok I see. So no abstraction there - that's just for file name ending. Ok…

**Comment by hedefalk** [comment]
Please check how they handle it in the sublime package then and we'll do the same?

**Comment by hedefalk** [comment]
Too bad if we can't support old sass simutanously though…?

**Comment by hedefalk** [comment]
Can we do the same they have:

https://github.com/vuejs/vue-syntax-highlight/commit/22200e79a5b30f70519c313dcde4f0bf5a587bf9

**Comment by hedefalk** [comment]
Or does that mean that they just threw away old sass highlighting and mapped both scss and sass to sass?

**Comment by aidistan** [comment]
Yeah. I think we should just throw away the old sass highlighting (sass) and mapped both scss and sass to **scss** (not sass)?

**Comment by aidistan** [comment]
`{ test: /.scss$/, loader: "style!css!sass" }` only works for `.scss` files processed by Webpack, not for `<style lang="scss">...</style>` codes. Since the latter one has already been processed by `vue-loader` through `scss-loader` (not exists, will raise an error).

The problem has existed for a loong time, and not well been handled by `vue-loader` and `vue-syntax-highlight`. I guess maybe the majority of the Vue community are `Sublime - Stylus` guys :sweat:

**Comment by hedefalk** [comment]
Please consider PR for mapping both to scss then and I'll release right
away.

**Comment by aidistan** [comment]
Finally I manage to find a way to fix this by adding following lines in `webpack.config.js`:

``` js
module.exports = {
  // ...
  vue: {
    loaders: {
      scss: 'style!css!sass'
    }
  }
};
```

Now we can support both sass and scss simutanously in this way.

I suggest to add a notice for this common pitfall:

> Since the current version of `vue-loader` cannot handle correctly with sass/scss with defaults, following lines are suggested to be added to your `webpack.config.js`:
> 
> ```
> vue: {
>   loaders: {
>     sass: 'style!css!sass?indentedSyntax',
>     scss: 'style!css!sass'
>   }
> }
> ```

**Comment by hedefalk** [comment]
Cool! I'll add to readme and close.

**Comment by laander** [comment]
Just FYI, `vue-loader` seems to be using it's own fork of `style-loader` per default (`vue-style-loader`), so i had to install `style-loader` in order for Webpack not to break. Using the vue one instead, you could do this:

```
vue: {
  loaders: {
    sass: 'vue-style!css!sass?indentedSyntax',
    scss: 'vue-style!css!sass'
  }
}
```

**Comment by aidistan** [comment]
@laander Thxs.

**Comment by FTAndy** [comment]
@laander your way is not useful for me, I have to add style-loader in this vue-loader version

**Comment by zezic** [comment]
Any variants to support SASS-syntax (old indented syntax) autocomplete?

**Comment by andre-brdoch** [comment]
How would a solution for a [nuxt](https://nuxtjs.org/) project look like? Nuxt is taking care of the webpack config, and I am not sure what is the correct way to extend it.

 Syntax highlighting looks a bit off:
![image](https://user-images.githubusercontent.com/31482129/117438345-b9c6bd80-af31-11eb-869c-0bb3fdf4c281.png)
