### ISSUE TITLE
Using lang="ts" and "default" breaks highlighting

### ISSUE THREAD

**Issue by snaptopixel** [hedefalk/atom-vue#50]
![](https://cl.ly/281O3u380V14/Screen%20Recording%202016-12-16%20at%2009.45%20AM.gif)

**Comment by aidistan** [comment]
It's a bug of your `ts` grammar pakcage. I have reproduced this issue with `language-ts` and fixed it with `atom-typescript`.

**Comment by snaptopixel** [comment]
Sorry I don't totally understand... How did you fix it? Do I just need to reinstall atom-typescript? Thanks for the help...

**Comment by snaptopixel** [comment]
Thanks for the info @aidistan, I've got it all working now 😄
