### ISSUE TITLE
Working with scopes

### ISSUE THREAD

**Issue by claytonrcarter** [hedefalk/atom-vue#54]
I'm trying to apply different indention rules to the HTML and JS portion of my vue files.  When I log scope in the `<template></template>`, I get `text.html.vue`, while in the `<script></script>`, the scope is logged as `text.html.vue` and `source.js.embedded.html`.

Is it possible to target a combination of scopes in my config, so that I can apply 1 set of indentation rules to `text.html.vue` and another to `text.html.vue + source.js.embedded.html`, or something?  If not, is there any chance we could add an additional scope that just targets the html/template portion of the file?

**Comment by aidistan** [comment]
Please refer to https://github.com/atom/atom/pull/3718

**Comment by claytonrcarter** [comment]
Thanks for following up on this.  The [Atom Flight Manual](http://flight-manual.atom.io/behind-atom/sections/scoped-settings-scopes-and-scope-descriptors/) was also helpful.  I have tried several different combinations of selectors, but the `.html.text.vue` scope seems to be taking priority over everything else.  My config has all of these (I know the last 3 are redundant, but none of them work):

```
".html.text.vue":
  editor:
    tabLength: 2
".source.js.embedded.html":
  editor:
    tabLength: 4
".text.html.vue .source.js.embedded.html":
  editor:
    tabLength: 4
".text.html.vue.source.js.embedded.html":
  editor:
    tabLength: 4
```

but the `<script></script>` is still using the `tabLength` of 2 from the `.html.text.vue`.  If I remove that first section, I get `tabLength`s of 4, but lose the `tabLength` of 2 in the `<template></template>`.  Am I missing/forgetting about a selector combo that would work here?

**Comment by aidistan** [comment]
Guess the feature has been broken by accident? I have tried the example given in that PR:

```
'.source.gfm':
  editor:
    softWrap: true
'.source.gfm .code':
  editor:
    softWrap: false
```

It doesn't work as expected either.

**Comment by aidistan** [comment]
Close this issue due to 3rd party issues.
