### ISSUE TITLE
My property is still unable to highlight 

### ISSUE THREAD

**Issue by deronendless** [hedefalk/atom-vue#57]
Property is gray, let me in the development process it is difficult to find my settings properties

**Comment by aidistan** [comment]
Hi @DeronEndless.

What property highlight? The one introduced in #21? Which version of the atom are you using?

Example code is needed to reproduce your issue and it's better to provide a screenshot with it.

**Comment by DanielMuller** [comment]
I had the same issue, turned out it was a conflict with other vue syntax packages I had installed.
Disabling **language-vue-component** fixed the issue.

**Comment by aidistan** [comment]
@DanielMuller Thanks for providing the info
