### ISSUE TITLE
How to add more snippets into ~/.atom/snippets.cson ?

### ISSUE THREAD

**Issue by albert-kam** [hedefalk/atom-vue#59]
I already installed language-vue, and try adding more snippet entries into my ~/.atom/snippets.cson.
Unfortunately these snippets aint working.

Do i have to add my own snippets into language-vue's snippets file ?

Please help

**Comment by aidistan** [comment]
Please refer to the preset example: https://github.com/hedefalk/atom-vue/blob/master/snippets/vue.cson

**Comment by albert-kam** [comment]
Yeah, i am following the example in that file.
Turns out my entries actually work after restarting Atom.

Thanks alot for your package, you bring back my sanity !
