### ISSUE TITLE
Cannot tab complete custom elements in .vue files

### ISSUE THREAD

**Issue by rchrdnsh** [hedefalk/atom-vue#63]
Not sure if this is should even be the job of this package, but tab completion for custom elements in .vue files, like `<router-link>` does not seem to be supported, so I have to manually create custom elements, which is not fun, to say the least. Just looking for a way to do this in atom, so I don't know if this package should support that, or if it should be the job of atom or another package.

**Comment by aidistan** [comment]
@rchrdnsh Sure what you want could be done through the snippets defined in this package. Please feel free to add those you like by sending PR requests.
