### ISSUE TITLE
SugarSS for PostCSS

### ISSUE THREAD

**Issue by Svenskunganka** [hedefalk/atom-vue#64]
I'm trying to get language-vue to highlight [SugarSS](https://github.com/postcss/sugarss) syntax for PostCSS, but to no avail. The syntax is supported by [language-postcss](https://github.com/azat-io/atom-language-postcss).

It's not super bad though, there's a bit of highlighting but color definitions gets a red block:

![Syntax](http://i.imgur.com/OmTjkGK.png)

**Comment by aidistan** [comment]
@Svenskunganka 
![selection_001](https://cloud.githubusercontent.com/assets/3037661/26437422/beb2c846-40e2-11e7-9d3f-8f20c8fb1054.png)

**Comment by Svenskunganka** [comment]
Lovely, thank you so much @aidistan!
