### ISSUE TITLE
Stylus doesn't autoindent on new line

### ISSUE THREAD

**Issue by kodekrendel** [hedefalk/atom-vue#67]
When using Stylus and hit enter second line is not auto-indent. When I work in `.styl` files standalone everythings working fine.

**Comment by aidistan** [comment]
Sorry but I can not reproduce this issue in my Atom. Everything works fine.

Please try to upgrade your Atom or the language package first.

**Comment by kodekrendel** [comment]
Yes, after selector. I have to tab by myself to write styles.
