### ISSUE TITLE
Syntax Hightlight Error When Use Stylus

### ISSUE THREAD

**Issue by visualxcode** [hedefalk/atom-vue#70]
in version 0.21.2,it‘s working well
![acafc4e3-4f1e-44f4-922a-31adfdb53039](https://user-images.githubusercontent.com/17687745/26874447-33ea8b26-4bb0-11e7-8717-d7747d006b6d.png)
but when i update it to 0.23.0,the hightlight is broken.
![5402e259-c2cc-41ad-aba5-d363dd809fe0](https://user-images.githubusercontent.com/17687745/26874508-799a38b0-4bb0-11e7-8871-3e053e89cbfe.png)

**Comment by aidistan** [comment]
It's due to a recent commit 80783d09d6669701c0c6ca9aebd2d8970e4a38d2 which moved `stylus` scope under `css` scope to respect the scope convention used in the most popular `stylus` language package for Atom.

Actually, the new version is the correct highlight for css codes, not the old one.

**Comment by aidistan** [comment]
See [the example](https://github.com/atom/one-dark-syntax#one-dark-syntax-theme) in the README of atom/one-dark-syntax to confirm that

**Comment by visualxcode** [comment]
thanks!
