### ISSUE TITLE
Components with pug templates does not allow line break before closing template tag

### ISSUE THREAD

**Issue by repoman** [hedefalk/atom-vue#74]
When line break present before closing template tag, the component javascript syntax highlighting fails. This is not an issue with jade.

Examples:

<img width="754" alt="skjermbilde 2017-08-28 kl 16 29 35" src="https://user-images.githubusercontent.com/233010/29778018-3e14665a-8c0e-11e7-9568-c9db469611bb.png">Broken JS syntax highlighting

<img width="781" alt="skjermbilde 2017-08-28 kl 16 29 05" src="https://user-images.githubusercontent.com/233010/29778021-442423e6-8c0e-11e7-90ac-48572305c000.png">Working JS syntax highlighting

**Comment by aidistan** [comment]
Actually, it is an issue with jade indeed.

![screenshot from 2017-09-01 23-43-05](https://user-images.githubusercontent.com/3037661/29977296-8fc94d20-8f02-11e7-9f12-864b4ce5a79c.png)
