### ISSUE TITLE
Adjacent JSX err

### ISSUE THREAD

**Issue by corysimmons** [hedefalk/atom-vue#75]
![image](https://user-images.githubusercontent.com/224636/29951993-6d9182f4-8e94-11e7-9ebd-8f1569c97dab.png)

**Comment by aidistan** [comment]
As said in the error message, it's a JSX-related issue.

Could you provide a full example to reproduce this issue?

**Comment by corysimmons** [comment]
Oops, this is Vueify's single file component stuff.

https://github.com/vuejs/eslint-plugin-vue fixes it.
