### ISSUE TITLE
kebab-case components aren't highlighted correctly

### ISSUE THREAD

**Issue by AMINEDGE** [hedefalk/atom-vue#76]
Hi I'm not sure whether this is a problem with atom html syntax or this extension
but as you know MultiWord Components should be written in kebab-case form because of case insensitive html elements, and when I put my vue components, they look like this
![image](https://user-images.githubusercontent.com/13257846/30003514-56210572-90d3-11e7-93df-30f42660a366.png)
tell me if I'm wrong but I thought maybe it would be a bug or something,
Thanks

**Comment by aidistan** [comment]
Are you sure it's related to this package? The original screenshot I received shows it's in a `php` file.

**Comment by AMINEDGE** [comment]
@aidistan Yes it’s a laravel blade (template engine) file which is based on php and html but I also changed the extension to html and the problem still was there

**Comment by aidistan** [comment]
Sorry, this package only works in `.vue` files, thus your issue has no relation to `atom-vue`.
