### ISSUE TITLE
Unable to target Vue component separator tags in Atom CSS

### ISSUE THREAD

**Issue by mniebling** [hedefalk/atom-vue#78]
I am not an expert in Atom customization so I apologize if this is a silly issue. My goal is to target the Vue component separator tags themselves (`<template>`, `<script>`, and `<style>`) with CSS selectors.

However, I can't figure out any way to select _only_ these lines. I thought it might involve the `.syntax--vue` or `.syntax--html` classes, but those appear to be added to every line in the component file. Is there any way to accomplish this?

**Comment by aidistan** [comment]
Hi @mniebling , sorry for this late reply. Hope following screenshot will help you:

![screenshot from 2017-12-07 16-14-29](https://user-images.githubusercontent.com/3037661/33705341-e0695978-db6a-11e7-9c91-ba63359430d0.png)

**Comment by mniebling** [comment]
Thanks for the reply! I was rather hoping to select the entire opening and closing tags, to fade them out a bit so the contents stand out more. No big deal though  :)

![image](https://user-images.githubusercontent.com/319534/33722921-e4b8a50e-db30-11e7-83cd-f2741d3492b8.png)
