### ISSUE TITLE
Multiple Extra Lines After Attribute List

### ISSUE THREAD

**Issue by superjoefly** [hedefalk/atom-vue#81]
Every time I hit 'enter' after defining an attribute within an HTML tag, an extra line is added. So if I define several attributes, each on a new line, I end up with several empty lines after the list of attributes.

Example:

```
      <q-fab
        color="primary"
          active-icon="alarm"
            direction="up"
              
            
          
        
      ></q-fab>
```

**Comment by robwierzbowski** [comment]
Just added this plugin on a fresh Atom install not experiencing this. Maybe the result of another plugin?

**Comment by superjoefly** [comment]
My bad...it's not this package...I think it has something to do with Emmet...
Thanks :-)
