### ISSUE TITLE
Use babel syntax if exist

### ISSUE THREAD

**Issue by alxtz** [hedefalk/atom-vue#84]
In the package currently, we use the `source.js` syntax scope to parse the `JavaScript` parts of vue components ( either inline or in `<script/>` )

![](https://user-images.githubusercontent.com/16031425/34653711-ccf04f18-f42a-11e7-9dd3-dda2f5c3189d.png)

But the default `source.js` isn't extremely useful, since the default `language-javascript` package doesn't work out of the box.
 
![image](https://user-images.githubusercontent.com/16031425/34653724-f5685b3e-f42a-11e7-87d5-8b0212c5bbf5.png)
( the `$method` is not getting highlighted, since `language-javascript` doesn't parse standalone variables )

if we add the new pattern `source.js.jsx` scope in the `patterns`, users that have installed `language-babel` could make use of the better javascript parsing.

![image](https://user-images.githubusercontent.com/16031425/34653747-5f0c9a46-f42b-11e7-970a-5cc7cbae93f9.png)

so we could keep javascript parsing up to date if you've installed `language-babel`

![image](https://user-images.githubusercontent.com/16031425/34653770-e9080078-f42b-11e7-848f-fc377e1254c8.png)

if `language-babel` is not installed, it would just fall to the default `language-javascript` parsing

![image](https://user-images.githubusercontent.com/16031425/34653783-1578de48-f42c-11e7-8203-43ce2a22e5fd.png)

I think this should be a cool feature to add, I can make a PR, too.

**Comment by aidistan** [comment]
@alxtz Sorry for no response and thanks for the report with detailed screenshots. This feature will be released in next version.
