### ISSUE TITLE
Feature request: HTML syntax highlighting in .vue files

### ISSUE THREAD

**Issue by madrus** [hedefalk/atom-vue#85]
Please add HTML syntax highlighting in .vue files.

**Comment by LAUVz** [comment]
As far as I know, it is there try disabling language-vue-component if you have it installed that one doesn't have syntax highlighting.

**Comment by madrus** [comment]
Thanks man! Disabling `language-vue-component` did not do the trick. But when I threw it away completely, I immediately got to see the colors. What a relieve! 👍

**Comment by aidistan** [comment]
Thanks @LAUVz for the solution. 

We recommend to use [language-vue](https://atom.io/packages/language-vue ) without `language-vue-component` installed :smile:
