### ISSUE TITLE
Feature request: Haml syntax highlighting in .vue files

### ISSUE THREAD

**Issue by thechrisoshow** [hedefalk/atom-vue#87]
Hi - just wondering how I can add Haml syntax to this?

(I don't mind making the changes if you can point me in the right direction).

**Comment by alxtz** [comment]
Hi, @thechrisoshow 
## The grammar file
I think the main syntax parse definition for each *-language package is inside the `grammar/vue.cson`
![](https://user-images.githubusercontent.com/16031425/37275148-643a3e68-2619-11e8-938c-2a5e54b6d0d1.png)
## What is does
Which you would define some queries like `begin`, `beginCaptures`, `end`, `endCaptures`, and what kind of language parse rule you would want to use for these elements
![](https://user-images.githubusercontent.com/16031425/37275307-c5a8bddc-2619-11e8-8f93-cae9184ca8b0.png)
For instance, here we would use the `#embedded-code` rule for the some comments like `<!-- vue comments -->`
![](https://user-images.githubusercontent.com/16031425/37275556-86f0942e-261a-11e8-9e3e-5bfdb29a9a66.png)
Which is defined in the lower part, and eventually try to use `source.*`, which is defined by other language packages

**Comment by aidistan** [comment]
Closed by #91
