### ISSUE TITLE
.vue style scss formatting to 4 spaces, ignoring settings

### ISSUE THREAD

**Issue by bbugh** [hedefalk/atom-vue#88]
Thanks for the awesome package, it works so much better than the vscode one. Funny how a little thing like functional auto formatting can make life so much better.

I've just switched over to `scss` from `css` in my components, and now my style blocks are formatting to 4 spaces. 💀I've tried adding `.sasslintrc` but I can't get it back to 2. All other formats (`css`, `js`, etc.) are correctly set to 2 based on my (default Vue) configuration. Is there an extra configuration thing I'm missing or is this a bug?

**Comment by aidistan** [comment]
Hi @bbugh, sorry for no response. Which auto formmatting package were you using?

**Comment by bbugh** [comment]
Hey, sorry, I’m not sure. I switched to VSCode a while ago (which still doesn’t handle auto formatting well). 

I believe I was probably using scsslint but I don’t remember. Sorry!
