### ISSUE TITLE
Atom 1.28.2 issues

### ISSUE THREAD

**Issue by alistairholt** [hedefalk/atom-vue#90]
I'm not 100% that atom-vue is responsible for the issues I'm experiencing since upgrading to Atom 1.28.2 but I've been experiencing strange and annoying behaviour when editing Vue Components. When pressing return, I'm getting a double return inserted. This happens everywhere in the component file – template, script and style and outside of these.

I have atom-vue 0.23.1 installed.

Any ideas?

Thanks

**Comment by alistairholt** [comment]
Having debugged a little, it seems that [emmet](https://atom.io/packages/emmet) is causing the double returns although I'm only seeing it in Vue Component files 🤔

**Comment by aidistan** [comment]
Thnaks for the report. Look forward to any detail if there is anything we could do.
