### ISSUE TITLE
language-vue causes CPU usage spike

### ISSUE THREAD

**Issue by SKalt** [hedefalk/atom-vue#92]
Atom version: 1.30.0
package version: 0.23.1

I verified this by disabling all my installed non-core packages, then incrementally reactivating them. Toggling `language-vue` would cause a CPU usage spike. 
<img width="180" alt="screen shot 2018-09-10 at 11 34 04 am" src="https://user-images.githubusercontent.com/10438373/45307674-9d0e2980-b4ed-11e8-9f16-a79b4095317e.png">
The first spike is atom startup, then the plateau is when `language-vue` is activated.

**Comment by aidistan** [comment]
Hi @SKalt.

Currently, our package is just a grammar package with a few snippets. Highlight rendering is handled by the core of Atom rather than this package. I suggest you to redo the experiment on several Vue files with different sizes and check the results.

Looking forward to any new comment.

**Comment by SKalt** [comment]
Further experimentation determined activating <span title="like an idiot">both <a href="https://atom.io/packages/ide-vue">ide-vue</a> and this package at the same time</span> was the root cause of the cpu spike.
<details><summary>details in case future wanderers actually need this</summary>
Activating the package causes the CPU spike the immediately when I open a vue file.
Other diagnostics:

```
atom --version
# Atom    : 1.32.1
# Electron: 2.0.9
# Chrome  : 61.0.3163.100
# Node    : 8.9.3
atom --safe # disables all packages, eliminating the cpu spike
# at this point, I activate atom-vue and toggle ide-vue, facepalm, and write this reply
```
</details>

**Comment by aidistan** [comment]
@SKalt Thanks for the update. Guess it's a normal situation when using `ide-vue`.

On its startup, `ide-vue` starts a `vue-language-server` which is responsible to all Vue-related features. This `vue-language-server` would scan all files for linting and error checking, which could really cause a CPU spike if in a large Vue project.
