### ISSUE TITLE
Language server exceeded 

### ISSUE THREAD

**Issue by HDenizD** [hedefalk/atom-vue#93]
```
The Vue (Vetur) language server has exited and exceeded the restart limit for project 'X'.
```
Cant work with Atom and Vue since this because this causes a broken syntax highlight for Vue files.
Why is this happening?

**Comment by aidistan** [comment]
Hi @HDenizD, thanks for the report.

I have never met this issue before. Could you provide any example which could reproduce this issue? And maybe [this issue](https://github.com/atom/ide-typescript/issues/90#issuecomment-366836968) could help you.

**Comment by koalazub** [comment]
Receiving the same error in the Atom Beta at the moment. Can't use Atom at all in Vue. I've tried creating a new project and was able to reproduce.
