### ISSUE TITLE
Editor keeps on crashing after install.

### ISSUE THREAD

**Issue by abetrs** [hedefalk/atom-vue#95]
I installed this package and its great. Amazing what you have done with this. But it caused my editor to keep crashing repeatedly. I can confirm that this is the cause because after I uninstalled this the crashes stopped.

**Comment by aidistan** [comment]
Hi @abetrs, this is possibly caused by the conflict between `language-vue` and some other Atom package you have installed. Try to disable all other community packages first and enable one by one to find that package. This issue will be solved soon once we were able to reproduce it.

**Comment by abetrs** [comment]
I have five community packages installed and none of the others are even related to JS except for emmet. So I think it is highly unlikely that that is possible but I will try and get back to you.
