### ISSUE TITLE
Please add this function!

### ISSUE THREAD

**Issue by btdadada** [hedefalk/atom-vue#96]
In js file,when you press tab,it will enter multi-tabs,to alignment with previous line.But in vue file,it only enter one tab one time.Should you add this function?Thank you very much.

**Comment by aidistan** [comment]
Hi @btdadada, sorry for this late reply. This function has already been implemented by `language-javascript`, `language-jsx`, and other script language packages (depending on the `xxx` in your `<script lang='xxx'>`). Just check your language settings and the corresponding language package~
